#!/usr/bin/env perl
use strict;
use File::Basename;
use File::Spec;

# Purpose: run some sanity checks before pushing.

my %checks_to_run = (
    'pre-push' => [qw(allcommitted)],
);

my $orgpath = File::Spec->rel2abs(__FILE__);
my $path = $orgpath;
if ($path !~ m{/.git/hooks/}) {
    $path =~ s{/.git/hooks/.*}{};
} elsif ($path =~ m{/tools/}) {
    $path =~ s{/tools/.*}{};
    if ($orgpath =~ m{pre-}) {
        warn("this should be installed to .git/hooks/{pre-push}\n")
    }
} else {
    die("failed to find top of repository\n")
}
chdir($path) and die("cannot cd to $path: $!\n");

my $hook = $orgpath;
$hook =~ s{.*/}{};

my @checks = @{$checks_to_run{$hook}}
  or die("misconfiguration in $orgpath: no checks configured for hook $hook\n");

for my $check (@checks) {
    my $cmd = "tools/checks/$check";
    system($cmd) and die("$hook hook failed on $cmd\n");    
}
