#!/usr/bin/env perl
use strict;

my %aux = (
    'README.md'  => 'is required as a general description',
    '.gitignore' => 'must be present, ignore at least .git and .gitignore',
)

for my $f (keys(%aux)) {
    next if (-f $f);
    die("$f is missing: it ", $aux{$f}, "\n");
}