#!/usr/bin/env perl
use strict;
use File::Basename;
use File::Find;
use File::Spec;

# Purpose: check that every .go file has a test and that it works.

# Find the name of this module. This script **must** be tools/gotests.
my $top = File::Spec->rel2abs(__FILE__);
$top =~ s{/tools/gotests$}{};
$top =~ s{.*/}{};

my (@gotest, @errs);

sub wanted {
    my $f = $File::Find::name;
    $f =~ s{^./}{};

    return if ($f !~ m{.go$} or $f =~ m{_test.go$});
    return unless ($f =~ m{.go$});

    my $test = $f;
    $test =~ s{.go$}{_test.go};
    if (! -f $test) {
        push(@errs, "no testfile '$test' for $f");
    }
}

find({
    wanted => \&wanted,
    no_chdir => 1,
},  '.');

system("go test ./...") and push(@errs, "go test(s) failed");

for my $e (@errs) {
    print("tools/gotests: error: $e\n")
}
exit(1) if ($#errs > -1);