#!/usr/bin/env perl
use strict;
use File::Basename;
use File::Find;
use File::Spec;

# Purpose: check that every .go file has a test and that it works.

my %test_in_dir;

sub wanted {
    my $f = $File::Find::name;
    $f =~ s{^./}{};
    my $path = $f;
    $path =~ s{/[^/]*$}{};

    if ($f =~ m{_test.go$}) {
        $test_in_dir{$path} = 1;
        return;
    }
    if ($f =~ m{.go$}) {
        $test_in_dir{$path} = 0 unless ($test_in_dir{$path});
        return;
    }
}

find({
    wanted => \&wanted,
    no_chdir => 1,
},  '.');

my $test_found;
for my $dir (sort(keys(%test_in_dir))) {
    if ($test_in_dir{$dir}) {
        print("GOOD: $dir has tests, good.\n");
        $test_found = 1;
    } else {
        warn("BAD:  $dir contains no tests, you should add them!\n");
    }
}
if ($test_found) {
    system("go test ./...") and die("go test(s) failed");
}