#!/usr/bin/env perl
use strict;
use File::Basename;
use File::Spec;

# Purpose: check that everything is locally committed.

my $path = File::Spec->rel2abs(__FILE__);
$path =~ s{tools/checks/.*$}{};

open(my $if, "git status |") or die("cannot run `git status`: $!\n");
my @lines;
my $all_committed;
while (my $line = <$if>) {
    push(@lines, $line);
    $all_committed = 1 if ($line =~ m{nothing to commit, working tree clean});
}
if (not $all_committed) {
    for my $line (@lines) {
        print($line);
    }
    die("not everything is locally committed\n");
}
