#!/usr/bin/env perl
use strict;
use File::Basename;
use File::Spec;

# Purpose: check that everything is locally committed.

my $orgpath = File::Spec->rel2abs(__FILE__);
my $path = $orgpath;
if ($path !~ m{/.git/hooks/}) {
    $path =~ s{/.git/hooks/.*}{};
} elsif ($path =~ m{/tools/}) {
    $path =~ s{/tools/.*}{};
    if ($orgpath =~ m{pre-}) {
        warn("this should be installed to .git/hooks/{pre-push}\n")
    }
} else {
    die("failed to find top of repository\n")
}
chdir($path) and die("cannot cd to $path: $!\n");

open(my $if, "git status |") or die("cannot run `git status`: $!\n");
my @lines;
my $all_committed;
while (my $line = <$if>) {
    push(@lines, $line);
    $all_committed = 1 if ($line =~ m{nothing to commit, working tree clean});
}
if (not $all_committed) {
    for my $line (@lines) {
        print($line);
    }
    die("not everything is locally committed\n");
}
